name: Build and Deploy Hugo site

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main  # change to 'master' if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.111.3'  # specify the Hugo version you want

      # Step 3: Build the site using your custom theme
      - name: Build site
        run: hugo --minify --theme custom-theme

      # Step 4: Deploy to GitHub Pages using your PAT
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}   # <-- your PAT stored as a secret
          publish_dir: ./public
          force_orphan: true   # create gh-pages branch if it doesn't exist
