name: Build Hugo site

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main  # change to 'master' if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.111.3'  # specify the Hugo version you want

      # Step 3: Build the site with your custom theme
      - name: Build
        run: hugo --minify --theme custom-theme  # Hugo will use your custom theme folder and custom.css

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}  # Token dedicated to workflows
          publish_dir: ./public  # folder where Hugo outputs the compiled site
